services:
  app:
    container_name: mockitfast_app
    build:
      context: .
      dockerfile: build/Dockerfile
    ports: 
      - "${PORT}:${PORT}"
    env_file: .env
    volumes:
      - ./example/router.json:/code/router.json
    networks:
      - mockitfast
    restart: always

networks:
  mockitfast:
    driver: bridge